### ISSUE TITLE
Remove Gulpfile and Gruntfile

### ISSUE THREAD

**Issue by tancredi** [BGGrieco/EmanueleTuretta-#1]
Unless you're needing a build step, I would suggest taking off the Gulpfile and Gruntfile - they are not necessary.

Also, when it comes to it, I'd suggest you'd choose one task runner over the other (my personal favourite would be Gulp) - for many tasks, you won't even need it, as you can get away with using npm scripts and command line tools.

**Comment by BGGrieco** [comment]
Aye aye!

**Comment by BGGrieco** [comment]
Thanks, No idea what those files where for anyway, NetBeans just automatically creates them.

**Comment by tancredi** [comment]
Fam stop using NetBeans, download SublimeText, Atom or VisualStudio

**Comment by tancredi** [comment]
:)

**Comment by BGGrieco** [comment]
Yeah, I've been using Atom since late April, I really like it. I used NetBeans for these repos because most of them were college projects and we were thought to use NetBeans and dreamWeaver as IDEs. But I think I will be switching to Atom almost exclusively. I kinda like the NetBeans interface though.
